# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateField(null=True),
        ),
    ]
