# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='model',
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='desc',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exposure_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='iso',
            field=models.DecimalField(decimal_places=9, max_digits=10, null=True),
        ),
    ]
