# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170913_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=256)),
                ('iso', models.DecimalField(decimal_places=9, max_digits=10)),
                ('exposure_time', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Album')),
            ],
        ),
    ]
